### ISSUE TITLE
Use current UI locale

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-date-picker-flow#38]
Using `DatePicker` in Flow should integrate with the UI locale. Currently the date is shown as `MM/DD/YYYY` even if the UI locale is `Locale.ITALIAN` which should display `DD/MM/YYYY`.

**Comment by denis-anisimov** [comment]
This issue is not about locale at all actually.

The date format is not based on the locale. It's based on the _client side_ format function which doesn't know anything about server-side locale.

The fact is:
- the only way to set format on the client side is the function `formatDate` on the `i18n` object for the web component (note that this has no any relation to the value format).
- I don't see a proper way how this function may be exposed on the server side via API. We can use some format string (which is used in the `SimpleDateFormat` class e.g.) but it's far away from trivial to create a JS function based on format string.
- The additional challenge here is that it's not enough to provide  `i18n.formatDate` function but it's also required to provide `i18n.parseDate` accompanied function which should parse the date as a string to the date object. This function should be strictly connected to the `i18n.formatDate` function. Otherwise it won't work properly.

Currently you may customize the date format from the client side (only).

So as a result:
- this is very complicated ticket.
- I don't think it's possible to involve the locale here at all (please note that the format like `MM/DD/YYYY` has no any relation to the locale. Locale is used to localize names , e.g. if you use format `DD  MMM YYYY` then `MMM` will be represented by the month name which varies in different locales. But if you use `DD/MM/YYYY` then it will be always the same regardless of locale). The issue is challenging even without locale.
- What we may do is provide an API to set the date format string (like `DD/MM/YYYY`). But it's not clear how exactly to do it. As mentioned above the format `DD MMM YYYY`  means already that `MMM`  represents a month name (not digits) and it becomes very not trivial to parse this date format string to be able to create a JS function which reflects the format string.
- And it becomes even more complicated since the "parse" function should be created as well based on this format.

I cannot fix this issue.
It requires the design which is aware of described above implementation issues.

I may suggest at the moment only limited number of date formats (as enum e.g.) for which we may provide a hardcoded functions `i18n.formatDate` and `i18n.parseDate`.

**Comment by heruan** [comment]
Thank you @denis-anisimov for the clear analysis!

As I understand, using the Web Component is really easy to use an external library (e.g. Moment, Sugar) to customize `formatDate`/`parseDate` functions; of course this isn't doable in a Java API.

I see a couple of options:

1. implement JavaScript logic to parse/format strings like `DD MMM YYYY`, with localization support and all (very complicated, and it's reinventing the wheel);
2. using an external library which already has this logic (e.g. Moment).

If (as I guess) including an external library in the Web Component itself isn't an option, what about including the library in the Flow Component, for the Java API?

**Comment by pleku** [comment]
Thanks Giovanni, the external library is  a good option, the third one:
1) Modify the Web Component or add a connector so that we can handle formatting on the server side
2) Support only preselected formats that we have internal implementations for the client side
3) Use a client side llibrary for the formatting

**Comment by pleku** [comment]
Based on the amount of feedback on this and how many UIs will most likely use the date picker, and would wish to localize the currently shown value: we need to resolve this before RC and release a Beta version with the fix.

**Comment by pleku** [comment]
In discussions after the spikes #45 and #46 we decided that we will just pass the locale set from the server side to client side and use [`Date.toLocaleDateString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString) to format the selected date, or the user written date:
- by default, `DatePicker` uses the locale of the `UI` it is attached to
- there is `setLocale(Locale locale)` method for the `DatePicker` to switch to another locale
- there is a convenience constructor for setting the locale
- the locale is used for formatting the picked date value on the client side by using `Date.toLocaleDateString()`
- the locale & method is used also for when the user writes the date with keyboard to determine the value

Some implications:
- no custom formatting, separator or such is supported via the server side
- the I18N object we have for localizing the date picker could benefit from using the locale too, but that is not at the moment in the scope of this issue and should be looked at separately
  - follow up issue #TODO

### Acceptance Criteria
- The javadocs in `setLocale` for `DatePicker` describe what it applies to and how
  - it should link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
  - it should point out that certain mobile browsers will not use the locale
- The implementation has been tested to work for the desktop browsers and mobile browsers
- There is a demo for `DatePicker` where the user can see the difference in switching the locale

**Comment by ZheSun88** [comment]
@heruan Hi, which version of `date-picker` you are using, if I may know? we have reimplemented this Locale support and it has been shipped with `vaadin-date-picker-flow 1.1.0`. 
By the way, i think it would be good to open a new ticket with your issue, instead of commenting on a closed ticket.

**Comment by heruan** [comment]
Thank you @ZheSun88 for the feedback, I'm on 1.1.0 and I've opened a new issue as you suggest: #135.
