### ISSUE TITLE
SPIKE: Investigate supporting a limited set of formats from server side

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-date-picker-flow#46]
Based on the issue #38, investigate how well it could work to only support couple predefined formats from the server side Java API. The user needs to be able to define
- the locale to use
- pick the format from some predefined options that we support
- possibility to customize eg. the separator used ('/', ' ', '-')

**Comment by ZheSun88** [comment]
*Goal*:  support the different formattings in Date-Picker from server side
*Experiment*:
- supporting different separators , i.e. `3-21-2018`:
  - we can support different separators ('/', '-', '.' or ' ') with providing an API to overwrite the `i18n.formatDate` and `i18n.ParseDate` and this can be done via `executeJavaScript` from the java side to achieve.

- supporting different Date format 
  - the same as supporting different separators, we need to overwrite the `i18n.formatDate` and `i18n.ParseDate`, but because of the default way of parsing date, we need to do more changes on splitting the date based on the order of either `MM/DD/YYYY` or `DD/MM/YYYY`

![image](https://user-images.githubusercontent.com/31067185/37697460-b0a068b8-2ce5-11e8-94a1-f20888641903.png)
- providing the user a way to define the Locale
  -  It is doable with either using our `i18n` property set or using the [DateFormatSymbols](https://docs.oracle.com/javase/8/docs/api/java/text/DateFormatSymbols.html) provided from Java 8, 
```
DateFormatSymbols locale = new DateFormatSymbols(Locale.CHINA);
locale.getMonths();
locale.getShortMonths();
```
*Problems*:
1. we need to do a lot of JavaScript execution from server side and we should somehow hide this part, otherwise, there might be security issues. (same like using 3rd party library, a provided connector can be a solution)
2. with date format `DD/MMM/YYYY` (21/Mar/2018), Parsing this format is more difficult
3. so far, we can provide with limited Date formats like `DD/MM/YYYY`, `MM/DD/YYYY` or `YYYY/MM/DD`
but different format needs different ways to parse the date, that can be a hard coding task. 
4. Locale support with `DateFormatSymbols` is limited based on the `java.util.Locale` package, i.e. if we want to support finnish date picker, we need to do it manually like the example we use in our exist demo.

the example can be built form [here](https://github.com/vaadin/vaadin-date-picker-flow/tree/Spike/46)

**Comment by pleku** [comment]
Follow up on https://github.com/vaadin/vaadin-date-picker-flow/issues/38
