### ISSUE TITLE
Date format got changed when reopen the date picker inside dialog(RC3)

### ISSUE THREAD

**Issue by jcgueriaud** [vaadin/vaadin-date-picker-flow#96]
#Hello,

When I set the locale to the datepicker, open a dialog the date format is correct (french format). If I close the dialog and re-open it the date format is wrong (US format)

Here a running example: https://date-tester-vaadin10.herokuapp.com/date

And the code is here: https://github.com/jcgueriaud/test/blob/master/src/main/java/com/gmail/jeanchristophe/DatePickerView.java

I tried on multiple browsers (chromium on ubuntu, firefox on ubuntu, chrome on Windows 10).

Thanks,

**Comment by ZheSun88** [comment]
Fixed with vaadin/flow#4269 soon to be released in RC4

**Comment by denis-anisimov** [comment]
There are two totally different issues.
The one is a duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/122.

Another one is about datepicker date format.
Please do one of the following:
- reformulate this issue so that it's only about one problem (date format because the other one is a duplicate)
- close this one and create a new about date format only.

**Comment by jcgueriaud** [comment]
Ok I edit my 1st post and reformulate the issue.
That's quite hard to know where the issues are (inside a vaadin-grid-flow for a problem without grid).

**Comment by ZheSun88** [comment]
I have edited the title of this ticket to describe the issue.  If it is not correct, feel free to change it.

**Comment by jcgueriaud** [comment]
Thanks for editing the title.
Date format got changed and i18n configuration got changed. (label of month ...)

**Comment by Nightbringer42** [comment]
Same problem here, with and without i18n modification.
